### ISSUE TITLE
Models - Cafe incompleto

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#1]
Em models.py, criei apenas um esboço muito inicial de Cafe para conseguir colocar a história de favoritos, porque fazia referência. O esqueleto está bem enxuto e sem vários campos que o grupo pensou

<img width="671" alt="image" src="https://github.com/aguiarth/projetos2g3/assets/155742254/2e67e157-805b-4a42-a186-270750fec5ac">

**Comment by MatheusVelame** [comment]
Problema resolvido após adicionar mais campos na class Cafe(models.Model), e adicionar um def de detalhes para retornas as suas respectivas variáveis da class.

![Captura de tela 2024-04-24 162547](https://github.com/MatheusVelame/projetos2g3/assets/142419976/a10accdb-f9af-49c8-9b83-f33b5b79e516)
