### ISSUE TITLE
Navbar na área de cadastro não preenche toda a tela

### ISSUE THREAD

**Issue by luzianes** [MatheusVelame/projetos2g3#12]
A barra de navegação não preenche toda a tela da área de cadastro:

![Screenshot 2024-04-24 090115](https://github.com/MatheusVelame/projetos2g3/assets/144596701/d649c236-84e1-4d20-85bd-8593acd34a04)

**Comment by Manuelaamorim** [comment]
Resolvido alterando o css da navbar.

**Comment by biapereira2** [comment]
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419447/da72de4d-8a61-4644-9ed0-e8dc48dee302)
