### ISSUE TITLE
Cadastro - e-mail repetido leva a IntegrityError

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#14]
Tentei cadastrar um usuário com o e-mail "b@b.com". Depois, tentei cadastrar outro usuário com o mesmo e-mail. Isso é o que aparece para o usuário:

<img width="503" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/8e0448e5-86f0-4007-a3f2-45db339629a0">

**Comment by MatheusVelame** [comment]
Problema resolvido após adicionar um objects.filter de email na def da views.py, informando na tela que o Email já existe.

![Captura de tela 2024-04-24 170723](https://github.com/MatheusVelame/projetos2g3/assets/142419976/c27c9e1b-5356-4e9f-8743-9249d62f2445)
