### ISSUE TITLE
Cadastro - qualquer pessoa pode cadastrar uma cafeteria

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#15]
Mesmo sem login, qualquer pessoa pode cadastrar uma cafeteria - não é um erro de código, mas será q faz sentido para o negócio? Será que essa não é uma view com `@login_required`?

<img width="729" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/cb16e094-4820-4b29-b2f0-fda270658db8">

**Comment by aguiarth** [comment]
O código continua dessa forma - funciona, mas pode ser um problema de negócio. Se um usuário mal-intencionado quiser criar uma página falsa da cafeteria de outra pessoa, consegue fazer isso e pode manchar a imagem do negócio

**Comment by YgoRosa** [comment]
agora pra cadastrar uma cafeteria é obrigatório o usuário estar logado
