### ISSUE TITLE
Cadastro - cafeteria não consegue fazer login

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#16]
Ao cadastrar uma cafeteria, nenhum dos campos corresponde aos campos solicitados na página de login. A cafeteria não fornece nome de usuário nem senha no cadastro, então como faz login?

<img width="743" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/11695e34-8d6d-4229-853e-b4c85bef7cc6">

**Comment by Manuelaamorim** [comment]
O problema foi resolvido adicionar responsável no cadastro de cafeterias e alterar o login de nome de usuário para email do responsável.
