### ISSUE TITLE
Cadastro - cafeteria não tem como saber quais foram os erros no formulário

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#17]
Tentei criar um cadastro de uma cafeteria com os dados abaixo, mas não acontece nada quando clico em "cadastrar". O e-mail usado já é o de um cliente cadastrado, o link não está no formato de link e também testei com alguns campos em branco. Porém, em nenhum dos testes, o usuário tem como saber o que deu errado, pois não acontece nada na página e não há nenhum feedback:

<img width="761" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/75854965-576a-4537-82ed-7ad7cbfc0aa6">

**Comment by Manuelaamorim** [comment]
O cadastro foi resolvido ao conectar o front-end do cadastro ao back-end. Validações também foram resolvidas adicionando-as ao views.py.
