### ISSUE TITLE
Cadastro - cafeteria não consegue efetuar cadastro

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#18]
Tentei cadastrar uma cafeteria com os dados abaixo - nenhum dado existia anteriormente no banco de dados. Ao clicar em cadastrar, nada acontece:

<img width="463" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/d235d6c0-fc22-4453-971d-3f92b3b3ffb8">

Confirmando pelo shell, o cadastro não chega a ser efetuado - a história não escreve no banco de dados:

<img width="569" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/506b57f1-ca57-4943-9a4f-42ab0ed63097">

**Comment by biapereira2** [comment]
resolvido ajustandi labels e inputs do html da página
