### ISSUE TITLE
Cadastro - cliente - mensagem de "usuário já existe" não é visível

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#19]
Ao tentar cadastrar um usuário que já existe no banco de dados, a mensagem de feedback não é legível no navegador, muito no topo da página:

<img width="691" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/c2d81802-0232-49f0-bdd7-082a2101fef1">

**Comment by YgoRosa** [comment]
era um erro de template
