### ISSUE TITLE
Login sem cadastro - página de cadastro não existe

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#2]
O template `login.html` tem uma opção para criar cadastro caso o usuário não tenha conta ainda, mas isso não redireciona para canto algum, pois o cadastro de usuários/cafeterias não existe ainda no projeto. Vai dar erro no runserver da venv. 
Pra ajeitar, fica para quem for tocar essa parte de cadastros e souber os campos que devem ser preenchidos para cada tipo de perfil. 

<img width="674" alt="image" src="https://github.com/aguiarth/projetos2g3/assets/155742254/532fb63d-a474-4226-8972-b7610ed7c2c7">

**Comment by MatheusVelame** [comment]
Problema resolvido após criar o template cadastro_usuário.html e cadastro_cafeteria.html no projeto, e adicionar as urls no template login.html.

![Captura de tela 2024-04-24 162342](https://github.com/MatheusVelame/projetos2g3/assets/142419976/53a503b2-4944-4a64-966a-c097fa7d334b)
