### ISSUE TITLE
Cadastro - cliente - não há opção na interface para mudar de página

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#20]
Se o usuário estiver na página de cadastro, a única forma de sair dali pela interface é concluindo um cadastro. Deveria ter outra opção de interface, senão o usuário q desiste de fazer cadastro precisa escrever na URL ou usar a seta de voltar do próprio navegador

**Comment by biapereira2** [comment]
![WhatsApp Image 2024-04-24 at 23 13 13](https://github.com/MatheusVelame/projetos2g3/assets/142419447/fdc001a3-fc44-46e2-aa76-1094b1feeeed)

![WhatsApp Image 2024-04-24 at 23 12 36](https://github.com/MatheusVelame/projetos2g3/assets/142419447/ddd5a94e-0ca1-4c81-ba54-b3745d0313b7)
Resolvido adicionando navbar na página de cadastro tanto de usuários, quanto de cafeterias
