### ISSUE TITLE
Cadastro - botão não tem resposta do servidor

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#22]
Ao preencher o formulário abaixo e clicar em cadastrar, não há resposta do servidor:

<img width="364" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/8daf8e1b-2511-4903-a873-8d8c50d44568">

No cmd:

<img width="559" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/0f1a4fa0-a743-4390-8b65-69ef8de3c85a">

No navegador:

<img width="592" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/fc10df6f-8ddb-4d81-8468-620ad60fb539">

**Comment by Manuelaamorim** [comment]
Resolvido ao conectar o front-end ao back-end do cadastro de cafeterias. Se o cadastro for bem sucedido, redirecionará para uma página de sucesso. Caso contrário, aparecerá mensagem ao respectivo erro.
