### ISSUE TITLE
Cadastro - WhatsApp não pode informar country code

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#25]
Tentei cadastrar uma cafeteria com o dado 5581000000006 - o cadastro só aceita com DDD, rejeita o 55. A mensagem de erro é pouco legível:

<img width="766" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/172976dc-bf50-44e9-9ad4-4cbe4605e02d">

**Comment by biapereira2** [comment]
Resolvido ajustando a quantidade de  dígitos permitido no campo de telefone
