### ISSUE TITLE
Models - cafeterias e proprietários são um único objeto

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#27]
Da forma como criamos os models e views, existe um único objeto para cafeterias e proprietários. Isso não parece adequado e deve gerar dificuldades pra gente no código, além de problemas práticos e valor da solução. Por exemplo, se eu sou uma proprietária que tem duas cafeterias, eu precisaria criar 2 cadastros, o que já cansa o usuário só de pensar. 

Não vamos resolver isso agora, mas seria importante pensarmos se proprietários e cafés vão mesmo ficar uma coisa só

**Comment by Manuelaamorim** [comment]
O problema foi resolvido conectando o modelo de cadastro de cafeteria de acordo com o cadastro de usuário, onde nele o cliente informa se é proprietário, podendo, dessa forma, cadastrar cafeterias.
