### ISSUE TITLE
Cadastro/Django Admin - clientes e cafeterias não vão para Usuários

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#28]
Confirmamos com o professor que os dados de cadastro de qualquer pessoa que tente fazer login precisam ser escritos em Usuários no Django Admin.
Não está assim agora, mas precisamos olhar isso em algum momento

**Comment by Manuelaamorim** [comment]
O problema foi resolvido ao conectar o cadastro de usuário com o User do próprio Django, fazendo com que os usuários vão para "Usuários" no admin. E caso for proprietário, além de ir para "Usuários", o cliente também vai para o Grupo "Empresários".
