### ISSUE TITLE
Login - baixa acessibilidade com uso de cores

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#31]
[Para depois: lembrarmos de deixar a página acessível - testes WCAG2]

As cores nas opções de criar conta na interface de login estão com baixo contraste

<img width="706" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/f748d66c-03d6-4748-9e1d-2b2b09b2cb2d">

**Comment by Manuelaamorim** [comment]
O problema foi resolvido ao alterar a interface de protótipo de baixa para protótipo final.
