### ISSUE TITLE
Cadastro - horário de funcionamento - erro de preenchimento não é tratado

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#35]
Na página de cadastro de cafeterias, o campo de horário de funcionamento não sugere ao usuário o tipo de dado que espera, nem a formatação do texto (por exemplo, se espera números, ou um hífen como em `09-17h`, etc). Inseri o horário "z" e a página apenas recarregou, sem informar qual foi o erro e sem que eu soubesse se a conta chegou a ser criada:

<img width="762" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/449d742a-2b1f-4251-ac72-a714b721eb59">

**Comment by Manuelaamorim** [comment]
Como o campo é um Charfield, ou seja, campo de texto, o preenchimento se dá por um mini texto explicando o horário e dias de funcionamento.
