### ISSUE TITLE
Cadastro - erros de preenchimento não impedem criação de conta

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#36]
O print abaixo é o resultado da issue #35 , mas parece ser o que ocorre com todos os campos de preenchimento ao cadastrar uma cafeteria: quando um campo espera uma entrada específica de dados e o usuário digita errado, isso não impede a criação de conta, ainda que o usuário receba uma mensagem de erro:

<img width="942" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/bace457b-b0c4-4bf8-9f38-67df0d46a01b">

**Comment by Manuelaamorim** [comment]
O problema foi resolvido ao colocar validações na view da história: validação de CNPJ (apenas dígitos e apenas 14), e whatsapp (apenas dígitos e apenas 14), além do email ser de uso obrigatório do @.
