### ISSUE TITLE
Ausência da barra de pesquisa na Home

### ISSUE THREAD

**Issue by luzianes** [MatheusVelame/projetos2g3#38]
Falta implementar o mecanismo de busca (barra de pesquisa) na Home.

![Screenshot 2024-04-25 212115](https://github.com/MatheusVelame/projetos2g3/assets/144596701/61bee752-31ac-4426-83db-09de635147ce)

**Comment by MatheusVelame** [comment]
Problema resolvido ao implementar a funcionalidade de buscar alguma cafeteria, até mesmo na home do site
