### ISSUE TITLE
Exigência de URL para o Instagram da Cafeteria

### ISSUE THREAD

**Issue by luzianes** [MatheusVelame/projetos2g3#39]
Ao cadastrar uma cafeteria e informar um usuário do Instagram (@cafetestando), a aplicação exige que o campo seja alimentado com uma URL.

![Screenshot 2024-04-25 220336](https://github.com/MatheusVelame/projetos2g3/assets/144596701/ebf56001-b281-45d4-b141-64501de5a74a)

**Comment by Manuelaamorim** [comment]
O campo pede uma URL pois foi programado para o usuário inserir o link do seu instagram, e não o @ de seu perfil.
