### ISSUE TITLE
Página de detalhes não existe

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#4]
Não temos nenhuma página de detalhes das cafeterias até o momento

**Comment by MatheusVelame** [comment]
Problema resolvido após criar uma página de detalhes no template detalhes.html.

![Captura de tela 2024-04-24 162935](https://github.com/MatheusVelame/projetos2g3/assets/142419976/e3650930-4d0d-40fe-8a3f-d83eb5afc480)
