### ISSUE TITLE
Ausência de opção de alterar dados da cafeteria ou excluir cafeteria

### ISSUE THREAD

**Issue by luzianes** [MatheusVelame/projetos2g3#40]
A aplicação só permite incluir dados de uma cafeteria. Não permite excluir ou alterar os dados de uma cafeteria cadastrada.

![Screenshot 2024-04-25 221123](https://github.com/MatheusVelame/projetos2g3/assets/144596701/cf020f30-a040-4b75-99e3-5af8457abbcb)

**Comment by Manuelaamorim** [comment]
Foi adicionada à aplicação a função de 'editar cadastro', que permite que empresários editem os dados de suas cafeterias.
