### ISSUE TITLE
Ausência de opção de excluir cliente ou alterar dados do cliente

### ISSUE THREAD

**Issue by luzianes** [MatheusVelame/projetos2g3#41]
A aplicação não conta com a opção de excluir ou alterar os dado de um cliente já cadastrado.

![Screenshot 2024-04-25 221123](https://github.com/MatheusVelame/projetos2g3/assets/144596701/8f7632f7-0b19-4456-8a62-2a39b77f9c2e)

**Comment by Manuelaamorim** [comment]
O problema foi resolvido adicionando uma funcionalidade onde o cliente pode alterar seus dados.
