### ISSUE TITLE
Aplicação permite criar nova conta de cliente mesmo estando logado

### ISSUE THREAD

**Issue by luzianes** [MatheusVelame/projetos2g3#43]
Mesmo estando logado, a aplicação permite cadastrar outro cliente com sucesso. Além disso, não há como visualizar qual o cliente logado nem os seus dados.

![Screenshot 2024-04-25 222145](https://github.com/MatheusVelame/projetos2g3/assets/144596701/cbac4331-06fd-421c-b439-04cdecf42cba)
![Screenshot 2024-04-25 222203](https://github.com/MatheusVelame/projetos2g3/assets/144596701/4f45bcdf-bd50-4a8b-aaed-7585fb1d9bed)

**Comment by aguiarth** [comment]
estou com esse mesmo erro, está na página UserCadastro. Além de que permite criar uma nova conta, mostra as mensagens de favoritos e reservas dentro de user cadastro:

<img width="599" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/545314ef-fca0-416c-aa5e-d57617e03607">

**Comment by YgoRosa** [comment]
corrigido no commit: fe3cfc1, apenas tirei o botão de cadastrar usuário do header, e agora o usuário loga e cadastra na aba de login no canto superior direito
