### ISSUE TITLE
UserCliente impede reservar um café

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#44]
<img width="245" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/4b8f2135-f7c6-4c22-ba1a-a6ca5b17294c">

**Comment by aguiarth** [comment]
gente, esse bug persiste para contas antigas

**Comment by Manuelaamorim** [comment]
O problema foi resolvido ao ajustar UserCliente para lidar corretamente com reservas. O bug persiste em contas antigas pois o cadastro delas não constou com o ajuste.
