### ISSUE TITLE
Cafeterias com o mesmo nome

### ISSUE THREAD

**Issue by MatheusVelame** [MatheusVelame/projetos2g3#45]
o sistema permite cafeterias com o mesmo nome e número de wpp.
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419976/324bb7ee-1f23-4e6f-9233-1d6057c130ae)

**Comment by Manuelaamorim** [comment]
A questão de mesmo número de Whatsapp foi resolvida ao adicionaer uma validação na view de cadastro de cafeteria, que valida se o whatsapp já existe no banco de dados. O nome da cafeteria não é validado pois podem existir mais de uma cafeteria com o mesmo nome.
