### ISSUE TITLE
UserCadastro - erro DoesNotExist - impede criação de conta de proprietário

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#47]
Na página de login/criar uma conta, tentei cadastrar como proprietário um novo usuário:
F, f@f.com, username f, senha 123.

A página não prossegue com o cadastro e dá erro, novamente, no UserCadastro: `DoesNotExist at /UserCadastro/ - Group matching query does not exist.` 

<img width="403" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/f172cd13-9eeb-4ed5-8366-5c75e81fe48a">

**Comment by Manuelaamorim** [comment]
O cadastro não funcionou pois precisa criar um Grupo chamado "Empresários" no admin, na aba Grupos. Ao fazer isso, o cadastro irá funcionar.

**Comment by Manuelaamorim** [comment]
![image](https://github.com/MatheusVelame/projetos2g3/assets/142773064/6ed6d56c-1d9a-46fa-bd0d-37ab9c7e552e)
