### ISSUE TITLE
UserCadastro

### ISSUE THREAD

**Issue by borgearthur** [MatheusVelame/projetos2g3#48]
Menu com html estranho quando completo o cadastro 

![image](https://github.com/MatheusVelame/projetos2g3/assets/143144251/d0d36d4c-da0c-4002-8e52-263931d70867)
problema

**Comment by Manuelaamorim** [comment]
O problema foi resolvido apagando o css do html da página e linkando com um novo arquivo css.
![image](https://github.com/MatheusVelame/projetos2g3/assets/142773064/5d65a193-37f9-49c5-91a4-50192a0ff35a)
