### ISSUE TITLE
Detalhes2 - impede favoritar - NoReverseMatch at /favoritos/

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#49]
Gente, vi agora essa nova view detalhes2 inserida por Ygor, gerou um problema ao tentar favoritar um café desde um usuário cliente autenticado: 

<img width="605" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/b74420dd-4255-4882-8855-d0f0cc392e5b">

**Comment by borgearthur** [comment]
Resolvido no issue ffa73d1be645598afdc72e84fbc8fed0c71ca12e

- Adicionei versão da página sem usuário autenticado e direcionei favoritos apenas para a página autenticada pela url e view
