### ISSUE TITLE
UserCadastro - concentra mensagens de erro

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#50]
Ao tentar criar um novo usuário, a página de cadastro de clientes concentra várias mensagens de navegação:

<img width="610" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/641b6347-097d-4118-84b4-3103e933c850">

**Comment by aguiarth** [comment]
Isso ainda acontece. Estava logada como b@b.com, senha 123, e tive problemas das issues #44 e #46 . Então, fiz logout para criar um novo usuário do zero. Ao clicar em cadastrar um novo usuário, as mensagens do caminho anterior apareceram:

<img width="697" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/8b38e44c-2e8e-4687-9f6a-a63705363759">

**Comment by YgoRosa** [comment]
fechado no commit: 9bd4ebb
