### ISSUE TITLE
Reservas - Possível reservar fora do horário de funcionamento

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#52]
Criei o usuário zn, senha 123, tentei reservar o café "o", que funciona 18-20. Coloquei a reserva para 2 pessoas às 11h. Consegui prosseguir:

<img width="310" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/f8c2a21b-9cc3-4874-a434-ca1495a8809a">

**Comment by borgearthur** [comment]
Horário de funcionamento não foi construido como um horário e nem esta sendo usado no figma

**Comment by aguiarth** [comment]
Como a informação de horário de funcionamento não foi solicitada no cadastro, não há como verificá-lo na reserva - decidimos deixar assim mesmo
