### ISSUE TITLE
Reservas - Editar - No ReservaCafe matches the given query

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#53]
Estava logada como zn, senha 123, na aba "minhas reservas", e fui editar minha reserva existente. Ao clicar em editar, não consegui prosseguir - mensagem de erro:

<img width="396" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/1f0c7e0a-da6d-4178-88f2-d35142c346f6">

Essa história estava funcional antes, sem erros

**Comment by borgearthur** [comment]
estava reserva.cafe.id ao invés de reserva.id
