### ISSUE TITLE
Reservas - Excluir - No ReservaCafe matches the given query #53

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#54]
Não é mais possível excluir uma reserva. Essa história funcionava antes.

Assim como na issue #53 , estava logada como zn, senha 123, na aba "minhas reservas", e fui excluir minha reserva existente. Ao clicar em "excluir", não consegui prosseguir - mensagem de erro:

<img width="388" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/e030a8bb-bc86-4094-b64a-d89aa2f17b6a">

Como dá para ver pela URL, o botão "excluir" redirecionou para o link de editar reserva

**Comment by borgearthur** [comment]
estava reserva.cafe.id ao invés de reserva.id

**Comment by aguiarth** [comment]
@borgearthur , reabri a issue porque o "excluir" ainda estava redirecionando para a URL "editar". Resolvi isso no commit 642cbc9 - o problema era no template minhas_reservas.html, que colocou o botão de excluir dentro do escopo do formulário do botão de editar:

<img width="670" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/99e5e42a-53d5-414a-9183-8ade4aad529c">

Agora cada botão funciona com sua função respectiva, só que a forma exibida no card ficou estranha:

<img width="209" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/f476eeb2-b774-46cc-9887-41b48edf3570">

**Comment by borgearthur** [comment]
Adicionado um display flex no card no commit abc438709c548aa7dd47d53aecf0bd742d2790c7

![image](https://github.com/MatheusVelame/projetos2g3/assets/143144251/a7b12b8b-0bcf-49e2-856f-0293964b2eaa)
