### ISSUE TITLE
Mesmo adicionando a foto ao editar o perfil, a foto não aparece nesta página

### ISSUE THREAD

**Issue by lilymtbr** [MatheusVelame/projetos2g3#60]
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419881/2e470393-669b-4fc0-b7a0-7d07382d1665)

**Comment by Manuelaamorim** [comment]
o problema foi resolvido ao ajustar todos os parametros da imagem no django para "profile_image". No models, estava "profile_images" e, por isso, não estava funcionando.
![image](https://github.com/MatheusVelame/projetos2g3/assets/142773064/04706eb4-13b2-4a00-9823-c3fc2b7ef11c)
