### ISSUE TITLE
Ao editar um cafeteria, diferentemente de editar perfil, a pessoa tem que preencher tudo de novo.

### ISSUE THREAD

**Issue by lilymtbr** [MatheusVelame/projetos2g3#61]
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419881/b4d1bbe8-f80a-42de-a075-c429337aa889)

Ao editar um cafeteria, diferentemente de editar perfil, a pessoa tem que preencher tudo de novo, ao invés das informações estarem pré-preenchidas e eu poder apenas alterar o que eu quero.

**Comment by Manuelaamorim** [comment]
Apesar de não ser um problema, pois mesmo que os campos estejam em branco o usuário poderia deixar nulo e a informação se mantém, agora os campos ficam preenchidos com as informações, em vez de ficarem vazios.
