### ISSUE TITLE
Ao invés de excluir reserva, está aparecendo "avaliar"

### ISSUE THREAD

**Issue by lilymtbr** [MatheusVelame/projetos2g3#63]
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419881/efa64dd1-6cfa-4931-b2b2-9012a5a1ada2)

**Comment by MatheusVelame** [comment]
Não foi um problema, pois foi a data e a hora selecionada já havia passado, e após isso, não é mais possível excluir uma reserva depois de já ter acontecido, tendo a única opção de realizar a avaliação da cafeteria.
