### ISSUE TITLE
Além de estar com "Avaliar" ao invés de "Excluir Reserva", as vezes o usuário é redirecionado para a página de avaliar

### ISSUE THREAD

**Issue by lilymtbr** [MatheusVelame/projetos2g3#68]
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419881/64096329-7065-4770-8303-9e1130f50ec7)

**Comment by MatheusVelame** [comment]
Como já registrado na issue #63, o horário e a data marcada já foi passado, e desse modo, só é possível avaliar uma cafeteria, e não excluir uma reserva que já passou. Porém, na página da "minhas reservas", há a presença das cafeterias que eu reservei, sendo possível avalia-las também nessa página.

**Comment by lilymtbr** [comment]
O problema persiste, porque está instável, às vezes eu clico em "Avaliar" e ele vai para página de excluir, às vezes vai para a de avaliar mesmo.

**Comment by MatheusVelame** [comment]
Problema resolvido após alterar o "{% url 'excluir_reserva' reserva.id %}" para "{% url 'avaliar_cafe' reserva.cafe.id %}" na linha 184, no template minhas_reservas.html.
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419976/9de02445-3a8f-44b3-9142-7dce0597e1d7)
