### ISSUE TITLE
Wireframes de design não implementados

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#8]
Nenhuma interface está como os wireframes de design

**Comment by biapereira2** [comment]
![image](https://github.com/MatheusVelame/projetos2g3/assets/142419447/7340d2d5-0f35-4e47-b4e5-b0a0b2e5c597)
![WhatsApp Image 2024-04-24 at 23 12 36](https://github.com/MatheusVelame/projetos2g3/assets/142419447/37b6dada-3626-4a25-8b98-7fe0dc164a48)
![WhatsApp Image 2024-04-24 at 23 13 13](https://github.com/MatheusVelame/projetos2g3/assets/142419447/de2c7ed0-3604-4c82-b9f0-8643ae712db5)
Resolvido ao finalizar html e css das páginas de cadastro

**Comment by aguiarth** [comment]
Resolvido: para o SR2, seguimos a implementação conforme os protótipos no Figma
