### ISSUE TITLE
Página de enviar e-mail não solicita e-mail do usuário

### ISSUE THREAD

**Issue by aguiarth** [MatheusVelame/projetos2g3#9]
A mensagem pode ser escrita, mas de onde será enviada? ela já solicita o e-mail da pessoa logada?

<img width="543" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/a8064a52-7626-4582-8f2f-ec9626a7fe00">

Eu fiz o teste sem nenhum login e consegui enviar uma mensagem. De que e-mail saiu a mensagem e pra onde foi?
<img width="407" alt="image" src="https://github.com/MatheusVelame/projetos2g3/assets/155742254/9644308a-b32f-493b-b99d-2e3479726f05">

**Comment by luzianes** [comment]
Essa funcionalidade de envio de e-mail não será implementada, pois o meio de comunicação entre cliente-cafeteria escolhido pelo grupo, por sugestão da equipe de Design, foi o encaminhamento direto da mensagem para o Whatsapp inserido pela cafeteria em seu cadastro. No entanto, essa funcionalidade que seria o envio de mensagem não foi excluída da aplicação pois será adaptada para avaliação dos usuários, história que será implementada para apresentação no SR2.
